<?php

/**
 * This file is automatically generated. Use 'arc liberate' to rebuild it.
 *
 * @generated
 * @phutil-library-version 2
 */
phutil_register_library_map(array(
  '__library_version__' => 2,
  'class' => array(
    'ArcanistEcsLintLinter' => 'src/ArcanistEcsLintLinter.php',
    'PatchedPHPUnitArcanistUnitTestResultParser' => 'src/PatchedPHPUnitArcanistUnitTestResultParser.php',
    'PatchedPhpUnitTestEngine' => 'src/PatchedPhpUnitTestEngine.php',
  ),
  'function' => array(),
  'xmap' => array(
    'ArcanistEcsLintLinter' => 'ArcanistExternalLinter',
    'PatchedPHPUnitArcanistUnitTestResultParser' => 'ArcanistTestResultParser',
    'PatchedPhpUnitTestEngine' => 'ArcanistUnitTestEngine',
  ),
));
